### ISSUE TITLE
custom-errors-message doesn't work?

### ISSUE THREAD

**Issue by Arimanecro** [fastify/example#20]
Hi.
What am I doing wrong?
I got examples of the code from here -- https://github.com/fastify/fastify/blob/main/docs/Reference/Validation-and-Serialization.md#schemaerrorformatter
```
import ajvErrors from "ajv-errors";

const app = fastify({
  ajv: {
    customOptions: {
      jsonPointers: true,
      allErrors: true
    },
    plugins: [ajvErrors],
  },
}

const itemSchemaTpl = {
  type: "object",
  properties: {
    id: { type: "string" },
    title: { type: "string"},
  },
  required: ["id", "title"],
  errorMessage: {
    required: {
      title: "SHIIIIIT",
    },
  },
};
app.get("/items/:id", {
  schema: {
    response: {
      200:  itemSchemaTpl,
    },
  },
  handler: (req, res) => res.send({id:"2"})
});
```
Response is **{"statusCode":500,"error":"Internal Server Error","message":"\"title\" is required!"}**
**BUT I expected message - SHIIIIIT**

**Comment by Eomm** [comment]
Closed as duplicate https://github.com/fastify/fastify/issues/3678
