### ISSUE TITLE
Renew this repo

### ISSUE THREAD

**Issue by Eomm** [fastify/example#4]
Hi @fastify/fastify 
since this repo is not still used, could we organize it with a wide range of examples in a "monorepo" way?

It could be related to the [blog post](https://github.com/orgs/fastify/teams/fastify/discussions/51?from_comment=10#discussion-51-comment-10) in order to link a complete and working example, meanwhile, the blog has only some piece of code and nice slides 😜

Opening this issue after this review
Ref https://github.com/fastify/fastify/pull/1588/files#r277096324

**Comment by mcollina** [comment]
Definitely +1 to the idea!

**Comment by StarpTech** [comment]
I also like the idea. [next.js](https://github.com/zeit/next.js/tree/canary/examples) already practice it and it helps a lot. We should include this repo as a submodule in fastify or create a simple reference page to this repo.

**Comment by Ethan-Arrowood** [comment]
I'd be happy to do a typescript example
